# type properties
type height:
  value: 0.918
  unit: inch

depth of drive:
  value: 1.6
  unit: mm

#STL options:
#  - option: beveled foot

reduced foot XY:
  value: 1.5
  unit: mm

reduced foot Z:
  value: 1.5
  unit: mm

reduced foot mode: bevel

