# type properties
type height:
  value: 0.918
  unit: inch

depth of drive:
  value: 2.0
  unit: mm

reduced foot XY:
  value: 0.6
  unit: mm

reduced foot Z:
  value: 4.0
  unit: mm

reduced foot mode: pyramids

pyramid pitch:
  value: 1.0
  unit: mm

pyramid top length:
  value: 0.2
  unit: mm

pyramid foot height:
  value: 2.0
  unit: mm
